---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

suites:
  - name: server
    run_list:
      - beermapper
    attributes:
      beermapper:
        rails_env: development
        database:
          adapter: postgresql
        app_config:
          api_key: myrug
          secret_token: secret
      rvm:
        group_users:
          - root
          - deploy
      beermapper-postgres:
        database_user:
          username: root
          password: password
        database_name: beermapper_production
      beermapper-nginx:
        nginx:
          beermapper_domain_name: 'beermapper-dev.com'
        passenger:
          rails_env: 'development'
