---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

suites:
  - name: server
    run_list:
      - beermapper
    attributes:
      rvm:
        group_users:
          - root
          - deploy
      beermapper-postgres:
        database_user:
          username: root
          password: password
