name             'beermapper-users'
maintainer       'Dan Olson'
maintainer_email 'olson_dan@yahoo.com'
license          'All rights reserved'
description      'Installs/Configures beermapper-users'
version          '0.1.0'
