name             'beermapper'
maintainer       'Dan Olson'
maintainer_email 'olson_dan@yahoo.com'
license          'All rights reserved'
description      'Installs/Configures beermapper'
version          '0.1.0'

depends 'apt'
depends 'locale'
depends 'beermapper-users'
depends 'beermapper-rvm'
depends 'beermapper-postgres'
depends 'beermapper-nginx'
depends 'beermapper-node'
depends 'beermapper-firewall'
depends 'beermapper-imagemagick'
