name             'beermapper'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures beermapper'
version          '0.1.0'

depends 'apt'
depends 'locale'
depends 'beermapper-users'
depends 'beermapper-rvm'
depends 'beermapper-postgres'
